id: I490308E4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T21:20:40+00:00'
last_modified: '2022-06-08T13:14:21.316421+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27885
  title: རྫོང་གསར་མཁྱེན་བརྩེའི་རྟེན་ཁྲོད་ལས་རྟེན་གྱི་ནང་གཞུག་ཕྱོགས་བསྡུས་རིལ་བུ་ཁག་སོགས་ཀྱི་དཀར་ཆག་རིན་ཆེན་མཆོག་གི་མཛོད
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    34DF:
      image_group_id: I4684
      title: ''
      total_pages: 56
      order: 1
      base_file: 34DF.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
