id: P010389
initial_creation_type: ocr
source_metadata:
  id: bdr:W27885
  title: རྫོང་གསར་མཁྱེན་བརྩེའི་རྟེན་ཁྲོད་ལས་རྟེན་གྱི་ནང་གཞུག་ཕྱོགས་བསྡུས་རིལ་བུ་ཁག་སོགས་ཀྱི་དཀར་ཆག་རིན་ཆེན་མཆོག་གི་མཛོད
  author: ''
  volumes: {}
