id: P010389
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W27885
  title: རྫོང་གསར་མཁྱེན་བརྩེའི་རྟེན་ཁྲོད་ལས་རྟེན་གྱི་ནང་གཞུག་ཕྱོགས་བསྡུས་རིལ་བུ་ཁག་སོགས་ཀྱི་དཀར་ཆག་རིན་ཆེན་མཆོག་གི་མཛོད
  author: ''
  volumes:
    974cbbd5777b42e0bb29b09539355de1:
      image_group_id: I4684
      title: ''
      volume_number: 1
      total_pages: 56
      base_file: v001.txt
